project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: about.ipynb
        text: About
      - href: slides\slides.ipynb
        text: slide
  

format:
  html:
    theme: cosmo
    toc: true



